### ISSUE TITLE
Kleiner Rechtschreibfehler in der home Komponente

### ISSUE THREAD

**Issue by rubberbandman62** [V-Peters/Angular#1]
![image](https://user-images.githubusercontent.com/338428/100994274-b67c6f80-3556-11eb-9768-adb46b363fd8.png)

**Comment by V-Peters** [comment]
Ist korrigiert, danke

 

Von: Hartwig Tödter <notifications@github.com> 
Gesendet: Donnerstag, 3. Dezember 2020 11:01
An: V-Peters/Angular <Angular@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [V-Peters/Angular] Kleiner Rechtschreibfehler in der home Komponente (#1)

 

 <https://user-images.githubusercontent.com/338428/100994274-b67c6f80-3556-11eb-9768-adb46b363fd8.png>
